name: 'subtree-splitter'
description: 'Sync your git repository subtree-splits'
inputs:
    config-path:
        required: true
        description: 'Configuration file path'
runs:
    using: 'node12'
    main: 'dist/index.js'
branding:
    icon: shuffle
    color: yellow
